// Generated by uniorm-gen. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include <uniorm/mapping/registry.hpp>

namespace gen_it {

// table: uniorm_gen_user
// index: PRIMARY (id) UNIQUE
struct UniormGenUser {
  std::int64_t id;  // BIGINT(19) PK NOT NULL
  std::string name;  // VARCHAR(64) NOT NULL
  std::optional<std::int32_t> age;  // INT(10) DEFAULT NULL
  std::optional<uniorm::timestamp> created;  // DATETIME(19) DEFAULT NULL
};

inline void register_UniormGenUser_mapping(uniorm::orm& registry) {
  registry.map<UniormGenUser>("uniorm_gen_user")
    .primary_key("id", &UniormGenUser::id)
    .column("name", &UniormGenUser::name)
    .column("age", &UniormGenUser::age)
    .column("created", &UniormGenUser::created);
}

// table: uniorm_gen_order
// FK: user_id -> uniorm_gen_user(id)
// index: PRIMARY (id) UNIQUE
// index: idx_gen_order_user (user_id)
struct UniormGenOrder {
  std::int64_t id;  // BIGINT(19) PK NOT NULL
  std::int64_t userId;  // BIGINT(19) NOT NULL
  std::string amount;  // DECIMAL(10,2) NOT NULL
  std::optional<std::string> note;  // VARCHAR(128) DEFAULT NULL
};

inline void register_UniormGenOrder_mapping(uniorm::orm& registry) {
  registry.map<UniormGenOrder>("uniorm_gen_order")
    .primary_key("id", &UniormGenOrder::id)
    .column("user_id", &UniormGenOrder::userId)
    .column("amount", &UniormGenOrder::amount)
    .column("note", &UniormGenOrder::note);
}

inline void register_gen_it_schema(uniorm::orm& registry) {
  register_UniormGenUser_mapping(registry);
  register_UniormGenOrder_mapping(registry);
}

}  // namespace gen_it
